library: ~/Music/.beets.db

plugins: bareasc edit embedart fetchart fish fromfilename info inline mbsync scrub zero

art_filename: AlbumArt
asciify_paths: yes
per_disc_numbering: yes

import:
  timid: yes

match:
  preferred:
    countries: ['XW', 'US', 'CA', 'GB|UK']
    media: ['Digital Media|File', 'CD']

paths:
  default: $albumartist/$album%aunique{}/$disc_track $title
  comp: Various Artists/$album%aunique{}/$artist - $title
  singleton: $albumartist/$title

edit:
  itemfields: disc track title artist album albumartist year genre
  albumfields: artist album albumartist year genre

embedart:
  auto: no

fetchart:
  cover_format: JPEG

item_fields:
  disc_track: u'%i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)

zero:
  fields: comments encoder #images
  update_database: yes
